# 8. NumPy 入門

## 8.1. NumPy を使う準備

In [1]:
# これは言うまでもない
import numpy as np

## 8.2. 多次元配列を定義する

In [2]:
# ベクトルを定義
a = np.array([1, 2, 3])

print(a)

[1 2 3]


`a.shape`で多次元配列の形がわかる  
要素が整数のタプルで返却される

In [3]:
print(a.shape)

(3,)


次元数は`ndim`という属性に保存されている  
これは`len(a.shape)`と同じ値になる  
今回、`a`というndarrayは1次元配列であるため、`a.shape`は要素数1のタプルで、  
`ndim`の値は1となる

次に3×3行列を定義してみる

In [4]:
# 行列を定義
b = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


形と次元数を調べる

In [5]:
print('Shape : ', b.shape)
print('Rank : ', b.ndim)

('Shape : ', (3, 3))
('Rank : ', 2)


次に`size`という属性も確認する  
この属性はndarrayがもつ要素数を表している  
今回`b`は3×3行列なので、要素数は9

In [6]:
print(b.size)

9


`np.array()`以外にも多次元配列を作る方法は色々ある  
代表例は以下の通り

`np.zeros((m, n))`：要素がすべて0の m×n行列を作る関数

In [7]:
# 形を指定して、要素がすべて0の ndarray を作る
# 3×3行列なので、関数には(3, 3)を代入
a = np.zeros((3, 3))

print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


`np.ones((m, n))`：要素がすべて1の m×n行列を作る関数

In [8]:
# 形を指定して、要素がすべて1の ndarray を作る
# 2×3行列なので、関数には(2, 3)を代入
b = np.ones((2, 3))

print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


`np.full((m, n), p)`：要素がすべて p の m×n行列を作る

In [9]:
# 形を指定して、指定した値のみを要素とする ndarray を作る
# 今回は3×2行列で、値が9なので、関数には"(3, 2), 9"を代入する
c = np.full((3, 2), 9)

print(c)

[[9 9]
 [9 9]
 [9 9]]


`np.eye(n)`：n×n の単位行列を作る関数

In [10]:
# 指定された大きさの単位行列を表す ndarray を作る
# 今回は5×5行列なので、関数には5を代入
d = np.eye(5)

print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


`np.random.random((m, n))`：要素がすべて0 ～ 1の乱数で構成される n×m行列を作る関数

In [11]:
# 形を指定して、0 ～ 1 の間の乱数を要素とする ndarray を作る
# 今回は4×5行列なので、関数には(4, 5)を代入
e = np.random.random((4, 5))

print(e)

[[0.47190393 0.13148177 0.83794986 0.80898626 0.48877384]
 [0.19548929 0.27767239 0.09309754 0.046176   0.49674092]
 [0.4247572  0.32516469 0.33658222 0.24423725 0.94363269]
 [0.43239399 0.67822813 0.97328985 0.53005883 0.47856505]]


`np.arange(n, m, p)`：n から始まり m になる（mは含まない）まで p ずつ増加する数列を作る関数

In [12]:
# 3 から始まり 10 の手前まで1ずつ増加する数列を作る
# ベクトルで返却される
f = np.arange(3, 10, 1)

print(f)

[3 4 5 6 7 8 9]


## 8.3. 多次元配列の要素を選択する

作成したndarrayのうちの特定の要素を選択して、値を取り出す方法を確認する。   
最もよく行われる方法は`[]`を使った添字表記（subscription）による要素の選択である。

### 8.3.1. 整数による要素の選択

上で作成した 4×5 行列`e`から 1 行 2 列目の値を取り出す  
i 行 j 列の要素を取り出す際には、`[i - 1, j - 1]`を指定する

In [13]:
val = e[0, 1]

print(val)

0.1314817694154884


### 8.3.2. スライスによる要素の選択

Pythonのリストと同様にスライス表記（slicing）を用いて選択したい要素を範囲指定することができる。  
ndarrayではさらに、カンマ区切りで複数の次元に対するスライスを指定できる。

In [14]:
# 4 × 5 行列 e の中央 2 × 3 = 6 個の値を取り出す
center = e[1:3, 1:4]

print(center)

[[0.27767239 0.09309754 0.046176  ]
 [0.32516469 0.33658222 0.24423725]]


`e`と`center`の形を比較してみる

In [15]:
print('Shape of e : ', e.shape)
print('Shape of center : ', center.shape)

('Shape of e : ', (4, 5))
('Shape of center : ', (2, 3))


また、インデックスを指定したり、スライスを用いて取り出した ndarray の一部に対し、値を代入することもできる

In [16]:
# 上の真ん中 6 個の値を 0 にする
e[1:3, 1:4] = 0

print(e)

[[0.47190393 0.13148177 0.83794986 0.80898626 0.48877384]
 [0.19548929 0.         0.         0.         0.49674092]
 [0.4247572  0.         0.         0.         0.94363269]
 [0.43239399 0.67822813 0.97328985 0.53005883 0.47856505]]


### 8.3.3. 整数配列による要素の選択

ndarrayの`[]`には、整数やスライスのほかに、整数配列を渡すこともできる。  
整数配列とは、ここでは整数を要素とするPythonリストまたはndarrayのことを指す。

In [17]:
a = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


このndarrayから、  
1. 1行2列目：`a[0, 1]`  
2. 3行2列目：`a[2, 1]`
3. 2行1列目：`a[1, 0]`  
の3つの要素を選択して並べ、形が`(3,)`であるようなndarrayを作りたいとする。

以下のように、順に対象の要素を指定して並べ、新しいndarrayにすることによっても実現はできる。

In [19]:
b = np.array([a[0, 1], a[2, 1], a[1, 0]])

print(b)

[2 8 4]


しかし、同じことを**選択したい行、選択したい列をそれぞれ順にリストとして与える**ことでも行える。

In [20]:
# 上と同じ表示を違う方法で
b = a[[0, 2, 1], [1, 1, 0]]

print(b)

[2 8 4]


**選択したい3つの値がどの行にあるか**だけに注目すると、それぞれ1行目、3行目、2行目にある要素。　　
ゼロベースインデックスでは、それぞれ0,2,1行目である。  
これが`a`の`[]`に与えられた1つ目のリスト`[0, 2, 1]`の意味である。  

同様に**列に着目**すると、ゼロベースインデックスでそれぞれ1,1,0列目の要素である。  
これが`a`の`[]`に与えられた2つ目のリスト`[1, 1, 0]`の意味となる。

## 8.4. ndarrayのデータ型

1つのndarryの要素は、すべて同じ型を持つ。  
NumPyでは様々なデータ型を使うことができるが、ここでは一部のみ確認する。  
NumpyはPythonリストを渡してndarrayを作る際に、その値からデータ型を推測する。  
ndarrayのデータ型は、`dtype`という属性に保存されている。

In [21]:
# 整数（Python の int 型）の要素を持つリストを与えた場合
x = np.array([1, 2, 3])

print(x.dtype)

int64


In [22]:
# 浮動小数点（Python の float 型）の要素を持つリストを与えた場合
x = np.array([1., 2., 3.])

print(x.dtype)

float64


以上のように、**Python の int 型は自動的に NumPy の int64 型**となった。また、**Python の float 型は自動的に NumPy のfloat64型**となった。
Python の int 型は NumPy の int_ 型に対応付けられており、Python の float 型は NumPy の float_ 型に対応付けられている。  
このint_ 型はプラットフォームによって int64 型と同じ場合と int32 型と同じ場合がある。float_ 型についても同様で、プラットフォームによって float64 型と同じ場合と float32 型と同じ場合がある。